
baseurl = "https://www.ericngigi.com"
title = "Eric Ngigi"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 10 #frontpage pagination
hasCJKLanguage = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "docs"

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "images/home_banner.webp"
  SEOTitle = "Leading with Innovation"
  description = "Eric Ngigi, Programmer, Open Source Enthusiast, Life Explorer | Here is Eric Ngigi's blog, discovering a bigger world with you."
  keyword = "Eric, eric, Eric's Blog, Web, PaaS, SaaS, Kubernetes, Microservice, Docker, Linux, Open-Source, DevOps"
  slogan = "Leading with Innovation"
  image_404 = "images/404/404.webp"
  title_404 = "You came to the wasteland without knowledge :("
  omit_categories = false

  # Sidebar settings
  sidebar_about_description = "Software Developer, Open Source Enthusiast and Life Adventurer"
  sidebar_avatar = "images/profile_image.webp"      # use absolute URL, seeing it's used in both `/` and `/about/`
  featured_tags = true
  featured_condition_size = 0
  support_button = true
  friends = false
  bookmarks = false
  about_me = true

  [params.social]
  rss            = false 
  email          = "ericmosesngigi@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  linkedin       = "https://www.linkedin.com/in/erik-ngigi"
  # stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/ErikNgigi"
  # wechat         = "your wechat qr code image"
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"

  # [[params.addtional_menus]]
  # title = "Projects"
  # href = "/more/projects/"
  # [[params.addtional_menus]]
  # title =  "Certifications"
  # href =  "/more/certifications/"
  [[params.addtional_menus]]
  title =  "About"
  href =  "/more/about/"
  # [[params.addtional_menus]]
  # title =  "Services"
  # href =  "/more/services/"

  [markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1
  [markup.highlight]
    style = "dracula"
